export default {
  facebook: "",
  twitter: "https://x.com/mingx94",
  instagram: "",
  youtube: "",
  linkedin: "https://www.linkedin.com/in/ming-hsuan-tsai94/",
  mastodon: "",
  github: "https://github.com/Mingx94",
  codepen: "",
  reddit: "",
  rss: "/rss.xml",
  email: "",
  bluesky: "https://bsky.app/profile/vartifact.cc",
  threads: "",
};
