/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.static.jsonc --include-runtime=false --env-interface=StaticEnv ./src/static-worker-configuration.d.ts` (hash: e216cb074e52f53002ece94107843eae)
interface __BaseEnv_StaticEnv {
	ASSETS: Fetcher;
	CMS: Fetcher /* blog */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./static-worker");
	}
	interface Env extends __BaseEnv_StaticEnv {}
}
interface StaticEnv extends __BaseEnv_StaticEnv {}
